<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220816144204 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE calendar (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(20) NOT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, description LONGTEXT NOT NULL, all_day TINYINT(1) NOT NULL, background_color VARCHAR(7) NOT NULL, border_color VARCHAR(7) NOT NULL, text_color VARCHAR(7) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE administration_type CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE administrator CHANGE type_id type_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE salary salary VARCHAR(50) DEFAULT NULL, CHANGE date_create date_create DATETIME DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE adresse adresse VARCHAR(50) DEFAULT NULL, CHANGE contact contact VARCHAR(50) DEFAULT NULL, CHANGE diplome diplome VARCHAR(100) DEFAULT NULL, CHANGE cin cin VARCHAR(50) DEFAULT NULL, CHANGE date_cin date_cin DATETIME DEFAULT NULL, CHANGE lieu_cin lieu_cin VARCHAR(50) DEFAULT NULL, CHANGE num_ae num_ae VARCHAR(150) DEFAULT NULL, CHANGE note_libre note_libre VARCHAR(255) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE class_room CHANGE section_id section_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE created_by_id created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE ecolage ecolage VARCHAR(100) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE class_subject CHANGE class_room_id class_room_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE profs_id profs_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE subject_id subject_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE coefficient coefficient VARCHAR(10) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE ecolage CHANGE student_id student_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE price price VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE emploi_du_temps CHANGE classe_id classe_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE matiere_id matiere_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE heure heure VARCHAR(100) DEFAULT NULL, CHANGE jour jour VARCHAR(100) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE history CHANGE user_act_id user_act_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE date_created date_created DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE reservation CHANGE room_id room_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE start start DATETIME DEFAULT NULL, CHANGE end end DATETIME DEFAULT NULL, CHANGE description description VARCHAR(150) DEFAULT NULL, CHANGE is_valid is_valid TINYINT(1) DEFAULT NULL, CHANGE is_fin is_fin TINYINT(1) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE room CHANGE is_reserved is_reserved TINYINT(1) DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE school_year CHANGE start_date start_date DATETIME DEFAULT NULL, CHANGE end_date end_date DATETIME DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE scolarite CHANGE type_id type_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE date_create date_create DATETIME DEFAULT NULL, CHANGE contact contact VARCHAR(50) DEFAULT NULL, CHANGE salary salary VARCHAR(100) DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE diplome diplome VARCHAR(100) DEFAULT NULL, CHANGE cin cin VARCHAR(50) DEFAULT NULL, CHANGE date_cin date_cin DATETIME DEFAULT NULL, CHANGE lieu_cin lieu_cin VARCHAR(50) DEFAULT NULL, CHANGE num_ae num_ae VARCHAR(150) DEFAULT NULL, CHANGE note_libre note_libre VARCHAR(255) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE scolarite_type CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE section CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE session CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE student CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE classe_id classe_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(30) DEFAULT NULL, CHANGE contact contact VARCHAR(80) DEFAULT NULL, CHANGE adresse adresse VARCHAR(50) DEFAULT NULL, CHANGE contact_parent contact_parent VARCHAR(50) DEFAULT NULL, CHANGE adresse_parent adresse_parent VARCHAR(50) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE student_note CHANGE student_id student_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE session_id session_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE subject CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE school_year_id school_year_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE roles roles JSON NOT NULL, CHANGE date_create date_create DATETIME DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deletedAt deletedAt DATETIME DEFAULT NULL, CHANGE imatriculation imatriculation VARCHAR(255) DEFAULT NULL, CHANGE photo photo VARCHAR(255) DEFAULT NULL, CHANGE prenom prenom VARCHAR(50) DEFAULT NULL, CHANGE birth_date birth_date DATETIME DEFAULT NULL, CHANGE sexe sexe VARCHAR(10) DEFAULT NULL, CHANGE birth_locale birth_locale VARCHAR(100) DEFAULT NULL, CHANGE is_enabled is_enabled TINYINT(1) DEFAULT NULL, CHANGE ets_name ets_name VARCHAR(255) DEFAULT NULL, CHANGE ets_logo ets_logo VARCHAR(255) DEFAULT NULL, CHANGE ets_hash_name ets_hash_name VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE calendar');
        $this->addSql('ALTER TABLE administration_type CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE administrator CHANGE type_id type_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE user_id user_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE salary salary VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date_create date_create DATETIME DEFAULT \'NULL\', CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE adresse adresse VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact contact VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE diplome diplome VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE cin cin VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date_cin date_cin DATETIME DEFAULT \'NULL\', CHANGE lieu_cin lieu_cin VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE num_ae num_ae VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE note_libre note_libre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE class_room CHANGE section_id section_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE created_by_id created_by_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE ecolage ecolage VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE class_subject CHANGE class_room_id class_room_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE profs_id profs_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE subject_id subject_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE coefficient coefficient VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ecolage CHANGE student_id student_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE price price VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE emploi_du_temps CHANGE classe_id classe_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE matiere_id matiere_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE heure heure VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE jour jour VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE history CHANGE user_act_id user_act_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE date_created date_created DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE payment CHANGE user_id user_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE reservation CHANGE room_id room_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE start start DATETIME DEFAULT \'NULL\', CHANGE end end DATETIME DEFAULT \'NULL\', CHANGE description description VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_valid is_valid TINYINT(1) DEFAULT \'NULL\', CHANGE is_fin is_fin TINYINT(1) DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE room CHANGE is_reserved is_reserved TINYINT(1) DEFAULT \'NULL\', CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE school_year CHANGE start_date start_date DATETIME DEFAULT \'NULL\', CHANGE end_date end_date DATETIME DEFAULT \'NULL\', CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE scolarite CHANGE type_id type_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE user_id user_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE date_create date_create DATETIME DEFAULT \'NULL\', CHANGE contact contact VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE salary salary VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE diplome diplome VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE cin cin VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date_cin date_cin DATETIME DEFAULT \'NULL\', CHANGE lieu_cin lieu_cin VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE num_ae num_ae VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE note_libre note_libre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE scolarite_type CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE section CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE session CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE student CHANGE user_id user_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE classe_id classe_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE status status VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact contact VARCHAR(80) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE adresse adresse VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact_parent contact_parent VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE adresse_parent adresse_parent VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE student_note CHANGE student_id student_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE session_id session_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE subject CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE user CHANGE school_year_id school_year_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE date_create date_create DATETIME DEFAULT \'NULL\', CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deletedAt deletedAt DATETIME DEFAULT \'NULL\', CHANGE imatriculation imatriculation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE photo photo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE prenom prenom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE birth_date birth_date DATETIME DEFAULT \'NULL\', CHANGE sexe sexe VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE birth_locale birth_locale VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_enabled is_enabled TINYINT(1) DEFAULT \'NULL\', CHANGE ets_name ets_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_logo ets_logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ets_hash_name ets_hash_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
